import Providers from "./providers";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/ui/Header";

const rubik = localFont({
  src: "../assets/fonts/Rubik-VariableFont_wght.ttf",
  display: "swap",
});

export const metadata = {
  title: "Frontend Quiz App",
  description: "Generated by Hüseyin Can Çirkin",
};

export default function RootLayout({ children, params }) {
  return (
    <html className="light" style={{ colorScheme: "light" }} lang="en">
      <body className={rubik.className}>
        <Providers>
          <header>
            <Header />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
